services:
  project-management:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - database
    restart: always
    networks:
      - project-management-network

  database:
    image: postgres:latest
    container_name: project-management-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # Added /data (PostgreSQL stores data here)
    networks:
      - project-management-network

networks:
  project-management-network:
    driver: bridge

volumes:
  db_data: 